# Importing Data 

Pandas allow a few helpful methods to import data from different formats. [See Here](https://pandas.pydata.org/docs/user_guide/io.html) for supported formats and relevant documentation.

We are going to use [read_csv()](https://pandas.pydata.org/docs/reference/api/pandas.read_csv.html#pandas.read_csv) to import a sample CSV file. The dataset is downloaded from Kaggle. You can download the dataset and see what other people have done with it here: https://www.kaggle.com/datasets/sidtwr/videogames-sales-dataset

In [1]:
import pandas as pd
games = pd.read_csv('PS4_GamesSales.csv', encoding='unicode_escape')

In [2]:
games.shape # get the row & columns count

(1034, 9)

In [3]:
games.head(10)

,Game,Year,Genre,Publisher,North America,Europe,Japan,Rest of World,Global
0,Grand Theft Auto V,2014.0,Action,Rockstar Games,6.06,9.71,0.60,3.02,19.39
1,Call of Duty: Black Ops 3,2015.0,Shooter,Activision,6.18,6.05,0.41,2.44,15.09
2,Red Dead Redemption 2,2018.0,Action-Adventure,Rockstar Games,5.26,6.21,0.21,2.26,13.94
3,Call of Duty: WWII,2017.0,Shooter,Activision,4.67,6.21,0.40,2.12,13.40
4,FIFA 18,2017.0,Sports,EA Sports,1.27,8.64,0.15,1.73,11.80
5,FIFA 17,2016.0,Sports,Electronic Arts,1.26,7.95,0.12,1.61,10.94
6,Uncharted (PS4),2016.0,Action,Sony Interactive Entertainment,4.49,3.93,0.21,1.70,10.33
7,Spider-Man (PS4),2018.0,Action-Adventure,Sony Interactive Entertainment,3.64,3.39,0.32,1.41,8.76
8,Call of Duty: Infinite Warfare,2016.0,Shooter,Activision,3.11,3.83,0.19,1.36,8.48
9,Fallout 4,2015.0,Role-Playing,Bethesda Softworks,2.91,3.97,0.27,1.34,8.48

In [4]:
games.tail(3)

,Game,Year,Genre,Publisher,North America,Europe,Japan,Rest of World,Global
1031,The Mummy Demastered,NaN,Action,NaN,0.0,0.0,0.0,0.0,0.0
1032,Project Nimbus: Code Mirai,NaN,Action,NaN,0.0,0.0,0.0,0.0,0.0
1033,Battle Chef Brigade,NaN,Action,NaN,0.0,0.0,0.0,0.0,0.0

# Sorting Data

Lets sort the data by global sales

In [5]:
well_sold_globally = games.sort_values(["Global"], ascending=[False])

In [6]:
well_sold_globally

,Game,Year,Genre,Publisher,North America,Europe,Japan,Rest of World,Global
0,Grand Theft Auto V,2014.0,Action,Rockstar Games,6.06,9.71,0.60,3.02,19.39
1,Call of Duty: Black Ops 3,2015.0,Shooter,Activision,6.18,6.05,0.41,2.44,15.09
2,Red Dead Redemption 2,2018.0,Action-Adventure,Rockstar Games,5.26,6.21,0.21,2.26,13.94
3,Call of Duty: WWII,2017.0,Shooter,Activision,4.67,6.21,0.40,2.12,13.40
4,FIFA 18,2017.0,Sports,EA Sports,1.27,8.64,0.15,1.73,11.80
...,...,...,...,...,...,...,...,...,...
817,Toukiden: The Age of Demons,2014.0,Action,Tecmo Koei,0.00,0.00,0.00,0.00,0.00
816,Pinball Arcade,2013.0,Misc,FarSight Studios,0.00,0.00,0.00,0.00,0.00
815,Soul Saga,NaN,Misc,NaN,0.00,0.00,0.00,0.00,0.00
814,Home - a Unique Horror Adventure,NaN,Misc,NaN,0.00,0.00,0.00,0.00,0.00
1033,Battle Chef Brigade,NaN,Action,NaN,0.00,0.00,0.00,0.00,0.00

__How about games that did not so well in Japan?__

In [7]:
poorly_in_japan = games.sort_values(["Japan"], ascending=[True])

In [8]:
poorly_in_japan.head()

,Game,Year,Genre,Publisher,North America,Europe,Japan,Rest of World,Global
516,MX vs. ATV Supercross Encore,2015.0,Sports,Nordic Games,0.0,0.05,0.0,0.01,0.06
713,The Witness,2016.0,Misc,"Thekla, Inc.",0.0,0.00,0.0,0.00,0.00
714,Quantic Dream Collection,2015.0,Action,Sony Computer Entertainment,0.0,0.00,0.0,0.00,0.00
715,Iwaihime: Matsuri,2017.0,Adventure,Nippon Ichi Software,0.0,0.00,0.0,0.00,0.00
716,RepKiss,2017.0,Adventure,Entergram,0.0,0.00,0.0,0.00,0.00

# God of War - Sales

How did the God of War series do?

In [11]:
gow_sales = games[games["Game"].str.lower().str.contains("god of war")]

In [12]:
gow_sales

,Game,Year,Genre,Publisher,North America,Europe,Japan,Rest of World,Global
17,God of War (PS4),2018.0,Action,Sony Interactive Entertainment,2.83,2.17,0.13,1.02,6.15
151,God of War III,2015.0,Action,Sony Computer Entertainment,0.40,0.33,0.02,0.15,0.89